---
###############################################################################
# Fail2ban Handlers
###############################################################################

- name: 'restart fail2ban'
  ansible.builtin.systemd:
    name:    'fail2ban'
    state:   'restarted'
    enabled: true
